networks:
  laravel:

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - database
    networks:
      - laravel

  database:
    image: mariadb:10.11
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  php:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  composer:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  npm:
    image: node:current-alpine
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - ./:/var/www/html
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel

  artisan:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    entrypoint: [ "php", "/var/www/html/artisan" ]
    networks:
      - laravel

volumes:
  mariadb:
